<a href="https://colab.research.google.com/github/GabrielaD1820/TallerNumPy/blob/main/tallernumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller de NumPy
Autor: Gabriela Díaz


Fecha: 10/04/2026

# Listas
------------------------------


In [ ]:
numeros = [10,20,30,40,50]
mixta   = [1, 'texto', 3.14, True]
vacia   = []
de_rango = list(range(1, 11))

Acceso por indices


In [ ]:
print(numeros[3])
print(numeros[-1])

40
50


Slicing [inicio : fin : paso]


In [ ]:
print(numeros[1:4]) #  Indices 1,2,3
print(numeros[:3])  #  desde el inicio hasta el índice 2 (0,1,2) que es n-1(3-1 = 2)
print(numeros[3:])  #  desde el índice N hasta el final (3.....)
print(numeros[::2]) #  cada os elementos desde le incio al final
print(numeros[::-1])#  Invertir la lista


[20, 30, 40]
[10, 20, 30]
[40, 50]
[10, 30, 50]
[50, 40, 30, 20, 10]


Metodos Principales

In [ ]:
numeros.append(60) # agregar al final de la lista 2 -> O(1)
numeros.insert(2, 99) #Insertar en la posicion 2 el numero 99  2 -> O(n)
numeros.remove(99)  #elimina la primera aparicion
numeros.pop()    #extare y debuelve el ultimo numero
print(len(numeros),numeros)



9 [10, 20, 30, 40, 50, 60, 60, 60, 60]


# Listas Comprehensions
--------------------------------------------

In [ ]:
cuadrados = [x**2 for x in range(1, 8)]
pares = [x for x in range(1, 21) if x % 2 == 0]

print(cuadrados)
print(pares)

[1, 4, 9, 16, 25, 36, 49]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


Comprehension anidada — genera una matriz

In [ ]:
#Tabla de multiplicar 3x3
tabla = [[i * j for j in range(1, 4)] for i in range(1, 4)]

print(tabla)

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


Con transformación de tipo

In [ ]:
palabras = ['hola', 'MUNDO', 'Python']
minusculas = [w.lower() for w in palabras]
print(minusculas)

['hola', 'mundo', 'python']


#Tuplas
--------------------------------------------------------------------------------

Creación

In [ ]:
coordenada = (3.5, -1.2) # tupla de 2 elementos
dimensiones = (28, 28, 3) # alto, ancho, canales (imagen RGB)
unitaria = (42,) # IMPORTANTE: la coma crea la tupla
no_tupla = (42) # esto es sólo el entero 42
print(coordenada)
print(dimensiones)
print(unitaria)
print(no_tupla, type(no_tupla))

(3.5, -1.2)
(28, 28, 3)
(42,)
42 <class 'int'>


Acceso

In [ ]:
print(dimensiones[0])
print(unitaria[-1])

28
42


In [ ]:
x, y =coordenada
alto, ancho, profundidad = dimensiones

print(x,y, alto, ancho, profundidad)

3.5 -1.2 28 28 3


Las tuplas son inmutables

In [ ]:
dimensiones[0] = 35  # esto genera un error

#Diccionarios
--------------------------------------------

Creación

In [ ]:
estudiante = {
'nombre': 'María',
'edad': 22,
'notas': [8.5, 9.0, 7.5],
'activo': True,
 0:'hola',
 123:'mundo',
 35.1:'234'
}

print(estudiante)


{'nombre': 'María', 'edad': 22, 'notas': [8.5, 9.0, 7.5], 'activo': True, 0: 'hola', 123: 'mundo', 35.1: '234'}


Acceso

In [ ]:
print(estudiante['nombre']) # 'María' — KeyError si no existe
print(estudiante.get('carrera', 'N/A')) # 'N/A' — valor por defecto seguro
#print(estudiante[35.1])


María
N/A


Modificacion

In [ ]:
estudiante['edad'] = 23 # modifica valor existente
estudiante['semestre'] = 6 # agrega nueva clave

Iteración

In [ ]:
for clave, valor in estudiante.items():
    print(f'{str(clave):12s} → {valor}')


nombre       → María
edad         → 23
notas        → [8.5, 9.0, 7.5]
activo       → True
0            → hola
123          → mundo
35.1         → 234
semestre     → 6


Dict comprehension

In [ ]:
cubos = {x: x**3 for x in range(1, 6)}
for i in cubos:
    print(cubos[i])

1
8
27
64
125


Otros métodos

In [ ]:
elementos = list(estudiante.keys())
print(elementos, type(elementos))

['nombre', 'edad', 'notas', 'activo', 0, 123, 35.1, 'semestre'] <class 'list'>


Verificar existencia de clave

In [ ]:
if 'nombre' in estudiante:
    print('la calve existe')

la calve existe


# Funciones
------------------------

Función básica

In [ ]:
def saludar(nombre):
     return f'Hola, {nombre}!'

saludo = saludar('Alice')
print(saludo)



Hola, Alice!


con parárametros por defecto

In [ ]:
def potencia(base, exponente=2):
    '''Eleva base a exponente. Por defecto calcula el cuadrado.'''
    return base ** exponente
print(potencia(5)) # 25 (usa exponente=2 por defecto)
print(potencia(2, 10)) # 1024

Retorno múltiple (devuelve una tupla)

In [1]:
def min_max(lista):
     return min(lista), max(lista) # empaqueta como tupla
minimo, maximo = min_max([3,1,7,2,5]) # desempaqueta
print(minimo, maximo)

1 7


Lambda — función anónima

In [2]:
doble = lambda x: x * 2
print(doble(8)) # 16
# Útil como argumento en funciones de orden superior
nums = [5, 2, 8, 1, 9, 3]
ordenados = sorted(nums, key=lambda x: -x) # orden descendente

16


map y filter

In [3]:
cuadrados = list(map(lambda x: x**2, nums))
mayores = list(filter(lambda x: x > 4, nums))

#Creación de Arrays

Array 1-D (vector)

In [6]:
import numpy as np
v = np.array([10, 20, 30, 40, 50])
print(v) # [10 20 30 40 50]
print(type(v)) # <class 'numpy.ndarray'>
print(v.dtype) # int64

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


Array 2-D (matriz)

In [7]:
M = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

Upcasting automático

In [8]:
mix = np.array([1, 2, 3.0]) # int + float → float64
print(mix.dtype)

float64


Forzar tipo de dato

In [9]:
float32 = np.array([1, 2, 3], dtype=np.float32)
booleano = np.array([0, 1, 0, 1], dtype=bool)
print(float32.dtype) # float32
print(booleano)

float32
[False  True False  True]


Arrays de ceros y unos

In [10]:
ceros = np.zeros((3, 4)) # matriz 3x4 de 0.0
unos = np.ones((2, 5)) # matriz 2x5 de 1.0
print(ceros.shape)

(3, 4)


Identidad

In [11]:
I = np.eye(4) # 4x4: 1 en diagonal, 0 fuera
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


arange vs linspace

In [12]:
# arange: define el PASO
a = np.arange(0, 10, 2)
# linspace: define la CANTIDAD de puntos
b = np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1. ] — stop incluido
print('arange: ', a)
print('linspace:', b)

arange:  [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


Aleatorios

In [13]:
np.random.seed(42) # semilla fija → reproducible
uniforme = np.random.rand(3, 4) # valores entre [0,1)
normal = np.random.randn(3, 4) # distribución normal (μ=0, σ=1)
enteros = np.random.randint(1, 10, size=(3, 3)) # enteros en [1, 10)
print(enteros)

[[3 7 4]
 [9 3 5]
 [3 7 5]]


Atributos del ndarray
Atributo Tipo / Valor típico

In [15]:
A = np.random.randint(0, 100, size=(4, 3, 2))
print('shape: ', A.shape) # (4, 3, 2)
print('ndim: ', A.ndim)
print('size: ', A.size) # 24 (4×3×2)
print('dtype: ', A.dtype) # int64
print('itemsize: ', A.itemsize) # 8 bytes por elemento
print('nbytes: ', A.nbytes)

shape:  (4, 3, 2)
ndim:  3
size:  24
dtype:  int64
itemsize:  8
nbytes:  192


 Diferencia entre shape de vector y matriz

In [16]:
v = np.array([1, 2, 3, 4, 5])
M = np.array([[1, 2, 3, 4, 5]])
print(v.shape) # (5,) → vector 1-D con 5 elementos
print(M.shape) # (1, 5) → matriz 2-D de 1 fila y 5 columnas
# Son numéricamente equivalentes pero estructuralmente distintos

(5,)
(1, 5)


Indexing — Acceso a Elementos

In [17]:
M = np.array([[10, 20, 30],
[40, 50, 60],
[70, 80, 90]])

Acceso a elementos individuales

In [18]:
print(M[0, 0]) # 10 → fila 0, columna 0
print(M[1, 2]) # 60 → fila 1, columna 2
print(M[-1, -1]) # 90 → última fila, última columna

10
60
90


Acceso a filas y columnas completas

In [19]:
# ':' en un eje significa 'todos los elementos de ese eje'
print(M[0, :]) # [10 20 30] → fila 0 completa
print(M[:, 1]) # [20 50 80] → columna 1 completa
print(M[-1, :]) # [70 80 90] → última fila

[10 20 30]
[20 50 80]
[70 80 90]


Tensor 3-D

In [20]:
T = np.arange(24).reshape(2, 3, 4) # 2 'páginas', 3 filas, 4 columnas
print(T[0]) # primera 'página' (matriz 3×4)
print(T[1, 2, 3]) # página 1, fila 2, columna 3
print(T[:, 0, :]) # primera fila de TODAS las páginas

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
23
[[ 0  1  2  3]
 [12 13 14 15]]


Slicing — Selección de Subconjuntos

In [21]:
A = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

Slicing básico

In [22]:
# [fila_ini:fila_fin , col_ini:col_fin]
sub = A[0:2, 1:3] # filas 0-1, columnas 1-2
print(sub)

[[2 3]
 [6 7]]


Omitir índices

In [23]:
print(A[:2, :]) # primeras 2 filas completas
print(A[1:, 2:]) # desde fila 1, desde columna 2

[[1 2 3 4]
 [5 6 7 8]]
[[ 7  8]
 [11 12]]


Con paso

In [ ]:
print(A[::2, ::2]) # filas pares, columnas pares

Vista vs. Copia

In [24]:
vista = A[0, :] # es una vista
copia = A[0, :].copy() # es una copia independiente
vista[0] = 999 # modifica A también!
copia[0] = 888 # NO modifica A
print(A[0, :]) # [999 2 3 4] ← vista modificó el original
print(np.shares_memory(A, vista)) # True
print(np.shares_memory(A, copia)) # False

[999   2   3   4]
True
False


Indexación Booleana

In [25]:

datos = np.array([[5, 12, 3, 18],
[7, 2, 15, 9],
[11, 6, 20, 1]])

Crear máscara booleana

In [26]:
mascara = datos > 10 # array de True/False con misma shape
print(mascara)
# [[False True False True]
# [False False True False]
# [ True False True False]]

[[False  True False  True]
 [False False  True False]
 [ True False  True False]]


 Aplicar máscara (filtro)

In [27]:
mayores = datos[mascara] # devuelve 1-D con los valores True
print(mayores)

[12 18 15 11 20]


Combinación de condiciones

In [28]:
# Valores entre 5 y 15 (inclusive)
rango = datos[(datos >= 5) & (datos <= 15)]
print(rango)

[ 5 12  7 15  9 11  6]


Modificar elementos con máscara

In [29]:
copia = datos.copy()
copia[copia < 5] = 0 # reemplaza valores menores a 5 con 0
print(copia)

[[ 5 12  0 18]
 [ 7  0 15  9]
 [11  6 20  0]]


np.where — condicional vectorizado

In [30]:
# np.where(cond, valor_si_True, valor_si_False)
resultado = np.where(datos > 10, datos, 0) # deja >10, reemplaza resto con 0
print(resultado)

[[ 0 12  0 18]
 [ 0  0 15  0]
 [11  0 20  0]]


Fancy Indexing

In [31]:
M = np.array([[10, 11, 12],
[20, 21, 22],
[30, 31, 32],
[40, 41, 42]])

Selección de filas por índice

In [32]:
indices = [0, 2, 3]
print(M[indices])

[[10 11 12]
 [30 31 32]
 [40 41 42]]


Selección en orden arbitrario (incluso repetido)

In [33]:
print(M[[3, 1, 3, 0]])

[[40 41 42]
 [20 21 22]
 [40 41 42]
 [10 11 12]]


Combinación con slicing

In [34]:
print(M[[0, 2], 1:])

[[11 12]
 [31 32]]


Fancy indexing de columnas

In [35]:
cols = [2, 0]
print(M[:, cols])

[[12 10]
 [22 20]
 [32 30]
 [42 40]]


Es siempre COPIA

In [36]:
copia = M[[0, 1]]
copia[0, 0] = 999
print(M[0, 0])

10


Reshape — Cambio de Forma

In [37]:
v = np.arange(12)

Reshape básico

In [38]:
M2x6 = v.reshape(2, 6) # 2 filas, 6 columnas
M3x4 = v.reshape(3, 4) # 3 filas, 4 columnas
M4x3 = v.reshape(4, 3) # 4 filas, 3 columnas
M2x2x3= v.reshape(2, 2, 3)

Uso de -1 (dimensión automática)

In [39]:
auto = v.reshape(-1, 3) # ?x3: NumPy calcula ? = 12/3 = 4 → shape (4,3)
print(auto.shape) # (4, 3)
auto2 = v.reshape(2, -1) # 2 x ?: ? = 12/2 = 6 → shape (2, 6)
print(auto2.shape)

(4, 3)
(2, 6)


flatten vs ravel

In [40]:
M = v.reshape(3, 4)
flat = M.flatten() # siempre COPIA
rav = M.ravel() # VISTA si es posible
flat[0] = 999
print(M[0, 0]) # 0 → flatten no modifica el original
rav[0] = 777
print(M[0, 0])

0
777


Agregar dimensiones

In [41]:
v1d = np.array([1, 2, 3, 4]) # shape (4,)
col = v1d.reshape(-1, 1) # shape (4, 1) — vector columna
fil = v1d.reshape(1, -1) # shape (1, 4) — vector fila
print(col.shape, fil.shape)

(4, 1) (1, 4)


#Operaciones Elemento a Elemento

In [42]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

Operaciones aritméticas básicas

In [43]:
print(a + b) # [11 22 33 44 55] suma elemento a elemento
print(b - a) # [ 9 18 27 36 45] resta
print(a * b) # [ 10 40 90 160 250] multiplicación
print(b / a) # [10. 10. 10. 10. 10.] división (devuelve float)
print(a ** 2) # [ 1 4 9 16 25] potencia
print(b // 3) # [ 3 6 10 13 16] división entera
print(b % 3) # [1 2 0 1 2]

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]
[ 3  6 10 13 16]
[1 2 0 1 2]


Operaciones con escalar (scalar broadcasting)

In [44]:
# El escalar se 'expande' para operar con cada elemento
print(a * 3) # [ 3 6 9 12 15]
print(a + 100) # [101 102 103 104 105]
print(a > 2)

[ 3  6  9 12 15]
[101 102 103 104 105]
[False False  True  True  True]


Matrices

In [45]:
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
print(M + N) # [[6,8],[10,12]] — suma elemento a elemento
print(M * N) # [[ 5 12],[21 32]] — producto elemento a elemento
# NOTA: M * N NO es el producto matricial. Para matrices usar M @ N

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


Broadcasting

Escalar + vector (caso más simple)

In [46]:
v = np.array([1, 2, 3, 4]) # shape (4,)
print(v + 10)

[11 12 13 14]


Vector + matriz

In [47]:
M = np.ones((3, 4)) # shape (3, 4)
v = np.array([10, 20, 30, 40]) # shape (4,) → se convierte a (1,4) → (3,4)
print(M + v)

[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


Columna + fila

In [48]:
col = np.array([[1], [2], [3]]) # shape (3, 1)
fil = np.array([10, 20, 30, 40]) # shape (4,) → (1, 4)
suma = col + fil # shape (3, 4)
print(suma)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


Normalización por columna (uso común en datos)

In [49]:
datos = np.random.randint(1, 100, (5, 3))
maximos = datos.max(axis=0) # shape (3,) — máximo de cada columna
norm = datos / maximos # broadcasting (5,3) / (3,) → (5,3)
print(norm.round(2))

[[0.03 0.11 0.57]
 [0.06 1.   0.98]
 [1.   0.33 0.95]
 [0.7  0.63 0.78]
 [0.98 0.26 1.  ]]


Verificar compatibilidad

In [51]:
# Shapes compatibles: (3,4) y (4,) → OK
# Shapes incompatibles: (3,4) y (3,) → Error (sin reshape)
try:
     err = np.ones((3,4)) + np.ones(3)
except ValueError as e:
     print('Error:', e)

Error: operands could not be broadcast together with shapes (3,4) (3,) 


Funciones Universales (ufuncs)

In [52]:
v = np.array([-4.5, -1.0, 0.0, 2.5, 9.0])

Funciones básicas

In [53]:
print(np.abs(v)) # [4.5 1. 0. 2.5 9. ]
print(np.sqrt(np.abs(v))) # raíz cuadrada (abs para evitar NaN)
print(np.square(v)) # [20.25 1. 0. 6.25 81. ]
print(np.floor(v)) # [-5. -1. 0. 2. 9.] — redondeo hacia abajo
print(np.ceil(v))

[4.5 1.  0.  2.5 9. ]
[2.12132034 1.         0.         1.58113883 3.        ]
[20.25  1.    0.    6.25 81.  ]
[-5. -1.  0.  2.  9.]
[-4. -1.  0.  3.  9.]


Exponencial y logaritmo

In [54]:
pos = np.array([1.0, 2.0, 4.0, 8.0])
print(np.log(pos)) # ln: [0. 0.693 1.386 2.079]
print(np.log2(pos)) # log₂:[0. 1. 2. 3.]
print(np.exp(pos))

[0.         0.69314718 1.38629436 2.07944154]
[0. 1. 2. 3.]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


Trigonometría (argumentos en radianes)

In [56]:
angulos = np.linspace(0, 2 * np.pi, 5) # 0, π/2, π, 3π/2, 2π
print(np.sin(angulos).round(4))
print(np.cos(angulos).round(4))

[ 0.  1.  0. -1. -0.]
[ 1.  0. -1. -0.  1.]


clip — limitar valores a un rango

In [57]:
datos = np.array([-10, -5, 0, 5, 10, 15, 20])
recortado = np.clip(datos, 0, 10) # valores entre 0 y 10
print(recortado)

[ 0  0  0  5 10 10 10]


maximum / minimum elemento a elemento

In [58]:
a = np.array([3, 1, 7, 2])
b = np.array([4, 5, 2, 8])
print(np.maximum(a, b)) # [4 5 7 8] — máximo entre pares
print(np.minimum(a, b))

[4 5 7 8]
[3 1 2 2]


Estadística y Reducciones

In [59]:
M = np.array([[4, 7, 2, 8],
[3, 11, 5, 1],
[6, 9, 0, 4]])

Reducción global (todos los ejes)

In [60]:
print(M.sum()) # 60
print(M.mean()) # 5.0
print(M.max()) # 11
print(M.min())

60
5.0
11
0


Reducción por eje

In [61]:
print(M.sum(axis=0)) # suma por columna: [13 27 7 13]
print(M.sum(axis=1)) # suma por fila: [21 20 19]
print(M.mean(axis=0)) # media de cada columna
print(M.max(axis=1)) # máximo de cada fila: [8 11 9]
# ── argmin / argmax — índice del extremo ───────────────────────────
print(M.argmin(axis=1)) # índice del mínimo en cada fila: [2 3 2]
print(M.argmax(axis=0))

[13 27  7 13]
[21 20 19]
[4.33333333 9.         2.33333333 4.33333333]
[ 8 11  9]
[2 3 2]
[2 1 1 0]


argmin / argmax — índice del extremo

In [62]:
print(M.argmin(axis=1)) # índice del mínimo en cada fila: [2 3 2]
print(M.argmax(axis=0))

[2 3 2]
[2 1 1 0]


std y var

In [63]:
print(M.std()) # desviación estándar global
print(M.var(axis=0))

3.1885210782848317
[1.55555556 2.66666667 4.22222222 8.22222222]


keepdims — mantener dimensiones

In [64]:
media = M.mean(axis=0, keepdims=True) # shape (1, 4) en vez de (4,)
print(media.shape) # (1, 4)
centrado = M - media

(1, 4)


cumsum — suma acumulada

In [65]:
v = np.array([1, 2, 3, 4, 5])
print(np.cumsum(v))

[ 1  3  6 10 15]


percentile

In [66]:
print(np.percentile(M, 25)) # percentil 25 (primer cuartil)
print(np.median(M))

2.75
4.5
