<a href="https://colab.research.google.com/github/GabrielaD1820/TallerNumPy/blob/main/Taller_Practicas_Numpy_ipynb_txt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practicas taller Numpy
Autor: Gabriela Díaz
Tema: NumPy
Fecha: 2026/04/23

Módulo 1 — Estructuras de Datos Python

Ejercicio 1: Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension.

In [ ]:
# Múltiplos de 7 entre 1 y 100
multiplos = [x for x in range(1, 101) if x % 7 == 0]
print(multiplos)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


Ejercicio 2: Dado el diccionario datos = {'a':10, 'b':25, 'c':7, 'd':18}
a) Crea una lista con las claves cuyo valor sea mayor a 12.
b) Crea un nuevo diccionario con esas claves y sus valores al cuadrado.


In [ ]:
datos = {'a':10, 'b':25, 'c':7, 'd':18}

# a) claves con valor > 12
claves = [k for k, v in datos.items() if v > 12]
print(claves)

# b) nuevo diccionario con valores al cuadrado
nuevo = {k: datos[k]**2 for k in claves}
print(nuevo)

['b', 'd']
{'b': 625, 'd': 324}


Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con:
longitud, suma, promedio, mínimo y máximo de la lista.


In [ ]:
def resumen(lista):
    return {
        'longitud': len(lista),
        'suma': sum(lista),
        'promedio': sum(lista)/len(lista),
        'min': min(lista),
        'max': max(lista)
    }

print(resumen([1,2,3,4,5]))

{'longitud': 5, 'suma': 15, 'promedio': 3.0, 'min': 1, 'max': 5}


Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5].

In [ ]:
def potencia(x, n):
    return x**n

lista = [1,2,3,4,5]

resultado = list(map(lambda x: potencia(x, 3), lista))
print(resultado)

[1, 8, 27, 64, 125]


In [ ]:
Módulo 2 — Creación y Atributos de Arrays

Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim):
a) Vector con enteros del 1 al 20.
b) Matriz de ceros de 5 filas y 3 columnas.
c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.


In [ ]:
# Múltiplos de 7 entre 1 y 100
multiplos = [x for x in range(1, 101) if x % 7 == 0]
print(multiplos)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.
Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].


In [ ]:
datos = {'a':10, 'b':25, 'c':7, 'd':18}

# a) claves con valor > 12
claves = [k for k, v in datos.items() if v > 12]
print(claves)

# b) nuevo diccionario con valores al cuadrado
nuevo = {k: datos[k]**2 for k in claves}
print(nuevo)

['b', 'd']
{'b': 625, 'd': 324}


Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y
np.array([1.0,2.0,3.0])? Verifica con código.


In [ ]:
def resumen(lista):
    return {
        'longitud': len(lista),
        'suma': sum(lista),
        'promedio': sum(lista)/len(lista),
        'min': min(lista),
        'max': max(lista)
    }

print(resumen([1,2,3,4,5]))

{'longitud': 5, 'suma': 15, 'promedio': 3.0, 'min': 1, 'max': 5}


Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal
es igual a 5 (usa np.trace()).


In [ ]:
def potencia(x, n):
    return x**n

lista = [1,2,3,4,5]

resultado = list(map(lambda x: potencia(x, 3), lista))
print(resultado)

[1, 8, 27, 64, 125]


Módulo 3 — Indexing, Slicing, Reshape


Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)
a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.
b) Extrae la segunda columna completa.
c) Extrae los elementos de los ángulos (esquinas) de la matriz.


In [ ]:
import numpy as np
A = np.arange(1, 26).reshape(5,5)

# a)
print(A[2:, :3])

# b)
print(A[:, 1])

# c)
print([A[0,0], A[0,-1], A[-1,0], A[-1,-1]])

[[11 12 13]
 [16 17 18]
 [21 22 23]]
[ 2  7 12 17 22]
[np.int64(1), np.int64(5), np.int64(21), np.int64(25)]


Ejercicio 2: Con la misma matriz A:
a) Crea una máscara booleana para los valores mayores a 12.
b) Reemplaza esos valores por -1 en una copia del array.
c) Usa np.where para reemplazar impares por 0 y mantener los pares.


In [ ]:
# a)
mask = A > 12
print(mask)

# b)
B = A.copy()
B[mask] = -1
print(B)

# c)
print(np.where(A % 2 == 0, A, 0))

[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


Ejercicio 3: Crea un vector de 24 elementos con arange(24).
Reorganízalo en: (a) matriz 6×4, (b) tensor 2×3×4, (c) vector fila 1×24.


In [ ]:
v = np.arange(24)

print(v.reshape(6,4))
print(v.reshape(2,3,4))
print(v.reshape(1,24))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento
en un slice y verifica que el array original también cambia.


In [ ]:
A = np.arange(10)
slice_A = A[2:6]

slice_A[0] = 999

print("Slice:", slice_A)
print("Original:", A)

Slice: [999   3   4   5]
Original: [  0   1 999   3   4   5   6   7   8   9]


Módulo 4 — Operaciones Numéricas y Manejo de Datos

Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).
a) Calcula la media, máximo y mínimo de cada columna.
b) Calcula la suma acumulada de la primera fila.
c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
Fórmula: (x - min_col) / (max_col - min_col)


In [ ]:
np.random.seed(7)
M = np.random.randint(1, 101, (5,4))

# a)
print("Media:", M.mean(axis=0))
print("Max:", M.max(axis=0))
print("Min:", M.min(axis=0))

# b)
print("Acumulada:", np.cumsum(M[0]))

# c)
min_col = M.min(axis=0)
max_col = M.max(axis=0)

norm = (M - min_col) / (max_col - min_col)
print(norm)

Media: [51.8 51.4 41.8 60.2]
Max: [84 91 93 90]
Min: [15 24  8 40]
Acumulada: [ 48 117 143 211]
[[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


Ejercicio 2: Usando broadcasting:
a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].
b) Suma ambos vectores y explica el shape del resultado.


In [ ]:
fila = np.array([1,2,3,4])
col = np.array([[10],[20],[30]])

res = fila + col

print(res)
print("Shape:", res.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Shape: (3, 4)


Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:
a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)
b) Imprime solo los nombres de esos estudiantes.


In [ ]:
nombres = np.array(["Ana","Luis","Pedro","Marta"])
notas = np.array([14,18,10,16])

prom = notas.mean()

mask = notas > prom

print("Cantidad:", np.sum(mask))
print("Nombres:", nombres[mask])

Cantidad: 2
Nombres: ['Luis' 'Marta']


Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.
Luego divide el resultado vertical en 3 partes iguales con vsplit.


In [ ]:
A = np.random.randint(1,10,(3,4))
B = np.random.randint(1,10,(3,4))

# concatenar
vert = np.vstack((A,B))
horiz = np.hstack((A,B))

print("Vertical:\n", vert)
print("Horizontal:\n", horiz)

# dividir
partes = np.vsplit(vert, 3)
for p in partes:
    print(p)

Vertical:
 [[1 8 7 4]
 [6 9 9 8]
 [6 1 1 3]
 [9 7 5 8]
 [4 4 9 4]
 [1 2 1 1]]
Horizontal:
 [[1 8 7 4 9 7 5 8]
 [6 9 9 8 4 4 9 4]
 [6 1 1 3 1 2 1 1]]
[[1 8 7 4]
 [6 9 9 8]]
[[6 1 1 3]
 [9 7 5 8]]
[[4 4 9 4]
 [1 2 1 1]]
